version: 2
jobs:
  build:
    docker:
      - image: circleci/python

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build
          command: |
              set -vxe
              docker build--progress plain  -t ncar/aws-cli:latest .
              verstr=`docker run --rm ncar/aws-cli --version 2>&1`
              version=`expr "${verstr}" : 'aws-cli/\([^ ]*\) .*'`
              if [ ":${version}" = ":" ] ; then
                  echo "Unable to determine version!"
                  exit 1
              fi
              echo version=${version}
              docker tag ncar/aws-cli:latest ncar/aws-cli:${version}
              printenv DOCKERHUB_PASSWORD | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
              docker push ncar/aws-cli

workflows:
    version: 2

    update:
        jobs:
            - build:
                context: sweg

    weekly:
        triggers:
            - schedule:
                cron: "0 0 * * 0"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - build:
                context: sweg



